name:                afp-summer-school
version:             0.1.0.0
github:              "githubuser/afp-summer-school"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  afp-summer-school-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - afp-summer-school

tests:
  afp-summer-school-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - afp-summer-school
    - QuickCheck
    - hspec
    - quickcheck-classes
